Ginekolog/urls.py
# from django.conf import settings
# from django.conf.urls.static import static
# from django.conf.urls.i18n import i18n_patterns  # for url translation
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from Ginekolog import settings
from ginekolog_app.views import flatpage

urlpatterns = [
    path('dashboard/', admin.site.urls),
    path('', include("ginekolog_app.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('page/<path:url>', flatpage, name='django.contrib.flatpages.views.flatpage'),
]
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# if not settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# handler404 = app_view.handle_404
# handler500 = app_view.handle_500
# Multilanguage --------------------------------------------------------------------------


# urlpatterns += i18n_patterns(
#     path('', include("ginekolog_app.urls")),
# ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# ----------------------------------------------------------------------------------------

# This is change default admin panel Headers and titles  ---------------------------------

admin.site.site_header = 'ADMINISTRATION'
admin.site.site_title = 'ADMINISTRATION'
admin.site.index_title = 'ADMINISTRATION'

# ----------------------------------------------------------------------------------------

ginekolog_app/urls.py
from django.urls import path

from ginekolog_app.views import BaseIndexView, AboutPageView, VideoListView, VideoDetailView, \
     PictureListView, PictureDetailView, PostListView, PostDetailView, SearchView

urlpatterns = [
    path('', BaseIndexView.as_view(), name='index'),
    path('about/<str:slug>/', AboutPageView.as_view(), name='about'),
    path('videos/', VideoListView.as_view(), name='videos'),
    path('video/<str:slug>/', VideoDetailView.as_view(), name='video-detail'),
    path('pictures/', PictureListView.as_view(), name='pictures'),
    path('picture/<str:slug>/', PictureDetailView.as_view(), name='picture-detail'),
    path('posts/', PostListView.as_view(), name='posts'),
    path('post/<str:slug>/', PostDetailView.as_view(), name='post-detail'),
    path('search/', SearchView.as_view(), name='search'),
]

ginekolog_app/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.flatpages.models import FlatPage
from django.db import models
from django.urls import reverse
from django.utils.html import mark_safe
from .tools.custom_tools import get_doctor_image_path, slugify, get_service_icon_path, \
    get_picture_path, get_post_cover_path, get_flatpage_cover_path, get_page_cover_path


# doctors model
class Doctors(models.Model):
    name = models.CharField(max_length=128, verbose_name="Name")
    surname = models.CharField(max_length=128, verbose_name="Surname")
    profession = models.CharField(max_length=128, verbose_name="Profession")
    phone_number = models.CharField(max_length=20)
    email = models.EmailField(max_length=128, null=True, blank=True, verbose_name="Email")
    address = models.CharField(null=True, blank=True, max_length=255, verbose_name="Address")
    profile_image = models.ImageField(null=True, upload_to=get_doctor_image_path, blank=True,
                                      verbose_name="Profile Photo")
    about = RichTextUploadingField(default='')
    description = models.CharField(max_length=255, default="", verbose_name="Short description", null=True, blank=True)
    work_grafic = models.CharField(max_length=255, default="", verbose_name="Work days", null=True, blank=True)
    status = models.BooleanField(default=True)
    slug = models.SlugField(max_length=255, null=True, blank=True)
    order = models.IntegerField(default=0)

    # logs
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    def __str__(self):
        return "Dr. %s %s" % (self.name, self.surname)

    def get_doctor_name(self):
        return "Dr. %s %s" % (self.name, self.surname)

    class Meta:
        ordering = ('order',)
        verbose_name = 'Doctor'
        verbose_name_plural = 'Doctors'

    def save(self, *args, **kwargs):
        super(Doctors, self).save(*args, **kwargs)
        self.slug = slugify("%s_%s" % (self.name, self.surname))
        super(Doctors, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('about', kwargs={'slug': self.slug})

    def get_image(self):
        if self.profile_image:
            return mark_safe("<img class='img-responsive' src='%s' alt="">" % self.profile_image.url)
        else:
            return mark_safe(
                "<img src='https://crestaproject.com/demo/nucleare-pro/wp-content/themes/nucleare-pro/images/no-image"
                "-box.png' alt='image' />")

    def get_image_thumbnail(self):
        if self.profile_image:
            return mark_safe("<img src='%s' style='width:300px;height:auto' alt='image' />" % self.profile_image.url)
        else:
            return mark_safe(
                "<img src='https://crestaproject.com/demo/nucleare-pro/wp-content/themes/nucleare-pro/images/no-image"
                "-box.png' alt='image' />")

    profile_image.short_description = "Profile Photo"
    profile_image.allow_tags = True


# Header menu base items model
class MenuBaseItems(models.Model):
    title = models.CharField(max_length=128, verbose_name="Menu title")
    order = models.IntegerField(default=0, verbose_name="Menu order")

    # logs
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        ordering = ('order',)
        verbose_name = 'Header base-menu item'
        verbose_name_plural = 'Header base-menu items'

    def __str__(self):
        return "%s" % self.title

    # return true if has child sub-menus
    def contain_dropdown(self):
        childCount = self.menusubitems_set.all().count()
        return True if childCount > 0 else False

    def get_childs(self):
        return self.menusubitems_set.all()


# Header menu sub-items model
class MenuSubItems(models.Model):
    title = models.CharField(max_length=128, verbose_name="Menu title")
    url = models.CharField(max_length=255, verbose_name="Redirect url")
    order = models.IntegerField(default=0, verbose_name="Menu order")
    base_header_item = models.ForeignKey("MenuBaseItems", null=True, blank=True, on_delete=models.CASCADE,
                                         verbose_name="Parent header menu")
    parent_sub_item = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE,
                                        verbose_name="Parent menu")

    # logs
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        ordering = ('order',)
        verbose_name = 'Header sub-menu item'
        verbose_name_plural = 'Header sub-menu items'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        super(MenuSubItems, self).save(*args, **kwargs)
        if not self.url.startswith("/") or not self.url[::-1].startswith("/"):
            url = ""
            for item in self.url.split("/"):
                if item != '':
                    url += item + "/"
            self.url = (url[::-1] + "/")[::-1]
            super(MenuSubItems, self).save(*args, **kwargs)

    def has_own_child(self):
        count = MenuSubItems.objects.filter(parent_sub_item=self).count()
        return True if count > 0 else False

    def has_own_parent(self):
        return True if self.parent_sub_item else False

    def get_childs(self):
        return MenuSubItems.objects.filter(parent_sub_item=self)

    def get_absolute_url(self):
        # return reverse('about', kwargs={'slug': self.slug})
        pass


# Services model
class Services(models.Model):
    title = models.CharField(max_length=128, verbose_name="Service title")
    content = models.CharField(max_length=128, verbose_name="Service content")
    icon = models.FileField(null=True, blank=True, upload_to=get_service_icon_path, verbose_name="Icon")
    order = models.IntegerField(default=0, verbose_name="Service order")

    # logs
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        ordering = ('-order',)
        verbose_name = 'Service'
        verbose_name_plural = 'Services'

    def __str__(self):
        return "%s" % self.title


# Services which count is assending
class CountingServices(models.Model):
    title = models.CharField(max_length=128, verbose_name="Service title")
    icon = models.FileField(null=True, blank=True, upload_to=get_service_icon_path, verbose_name="Icon")
    count = models.IntegerField(default=0, verbose_name="Service count")
    more = models.BooleanField(default=False, verbose_name="And more")
    order = models.IntegerField(default=0, verbose_name="Service order")

    # logs
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        ordering = ('-order',)
        verbose_name = 'Services with count'
        verbose_name_plural = 'Services with count'

    def __str__(self):
        return "%s" % self.title


# social network addresses
class SocialNetworkAddresses(models.Model):
    title = models.CharField(max_length=255, verbose_name="Social network address")
    url = models.URLField(max_length=255, verbose_name="Social network url")
    doctor_belongs_to = models.ForeignKey('Doctors', on_delete=models.CASCADE, verbose_name="Belongs to doctor")
    order = models.IntegerField(default=0, verbose_name="Icon order")
    # logs
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        ordering = ('-order',)
        verbose_name = 'Social Network Address'
        verbose_name_plural = 'Social Network Addresses'

    def __str__(self):
        return "%s" % self.title


# Videos model
class Video(models.Model):
    title = models.CharField(max_length=255, verbose_name="Video title")
    slug = models.SlugField(null=True, blank=True, )
    description = RichTextUploadingField(default='', verbose_name="Video description")
    url = models.URLField(max_length=255, verbose_name="Youtube URL")
    doctor_belongs_to = models.ForeignKey('Doctors', on_delete=models.CASCADE, verbose_name="Belongs to DR. ")
    category_belongs_to = models.ForeignKey("Category", null=True, blank=True, on_delete=models.CASCADE,
                                            verbose_name="Belongs to category ")

    # logs
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    def save(self, *args, **kwargs):
        super(Video, self).save(*args, **kwargs)
        self.slug = slugify("%s" % self.title)
        time_index = self.url.find('&t=')
        if time_index != -1:
            self.url = self.url[:time_index]
        super(Video, self).save(*args, **kwargs)

    class Meta:
        ordering = ('id',)
        verbose_name = 'Video'
        verbose_name_plural = 'Videos'

    def __str__(self):
        return "%s" % self.title

    def get_video_thumbnail_url(self):
        video_id_index = self.url.find("v=")
        video_id = self.url[ video_id_index+2:video_id_index+13 ]
        # https://i.ytimg.com/vi/YB2Gcpyjn1Q/hqdefault.jpg
        return "http://i3.ytimg.com/vi/%s/hqdefault.jpg" % (video_id)

    def get_video_thumb_admin(self):
        if self.url:
            video_id = self.url[::-1][:11]
            url = "http://i3.ytimg.com/vi/%s/hqdefault.jpg" % (video_id[::-1])
            return mark_safe("<img src='%s' style='width:300px;height:auto' alt='image' />" % url)
        else:
            return mark_safe(

ginekolog_app/forms.py
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from django.contrib.flatpages.forms import FlatpageForm

from .models import MyFlatPage


class FlatpageFormNew(FlatpageForm):
    class Meta:
        model = MyFlatPage
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(FlatpageFormNew, self).__init__(*args, **kwargs)
        self.fields['content'].widget = CKEditorUploadingWidget()

ginekolog_app/templates/Pages/home/index.html
{% load static %}
{% load tags %}

<section class="home">
    <div class="home-slider wow fadeIn">
        <div class="home-carousel owl-carousel owl-theme">
            {% for slider in sliders %}
                <div class="carousel-item">
                    <div class="carousel-backg" style="
                            background-image: linear-gradient(272deg, rgba(255,255,255,0),#ffffff),
                            url('{{ slider.slider_image.url }}');"></div>
                    <div class="container">
                        <div class="row">
                            <div class="carousel-item-content">
                                <h2>{{ slider.header|default:"" }}</h2>
                                <h5>{{ slider.sub_header|default:"" }}</h5>
                                <div class="carousel-text">
                                    {{ slider.description|default:"" }}
                                </div>
                                {% if slider.button_text %}
                                    <a class="btn-i" href="{{ slider.button_url }}">{{ slider.button_text }}</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="services">
        {% for service in services %}
            <div class="service-item">
                <div class="wow zoomIn" data-wow-delay="{{ forloop.counter|data_wow_delay }}">
                    <div class="service-item-img">
                        <img src="{{ service.icon.url }}" alt="">
                    </div>
                    <h3>{{ service.title }}</h3>
                    <p>{{ service.content }}</p>
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="doctors">
        <div class="container">
            <div class="row">
                <h1 class="section-title">Həkimlər</h1>
                {% for doctor in doctors %}
                    <div class="col-sm-6 col-md-6">
                        <div class="doctors-item">
                            <div class="doctor-img wow fadeInLeft">
                                <img class="img-responsive" src="{{ doctor.profile_image.url }}" alt="">
                            </div>
                            <div class="wow pulse" data-wow-iteration="1"
                                 data-wow-duration="{{ forloop.counter|data_wow_delay }}">
                                <h2>{{ doctor.get_doctor_name }}</h2>
                                <h5>{{ doctor.profession }}</h5>
                                <ul>
                                    {% for sn in doctor.socialnetworkaddresses_set.all %}
                                        <li>
                                            <a href="{{ sn.url }}">
                                                <i class="fa fa-{{ sn.title }}"></i>
                                            </a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="statistics">
        <div class="statistics-layer"></div>
        <div class="container">
            <div class="row">
                {% for service in c_services %}
                    <div class="col-xs-6 col-sm-3 col-md-3">
                        <div class="statistics-item">
                            <div class="statistic-img wow pulse">
                                <img class="img-responsive" src="{{ service.icon.url }}" alt="">
                            </div>
                            <span class="number">
                                <span class='counter-value' data-count="{{ service.count }}">0</span>
                                {% if service.more %}+{% endif %}
                            </span>
                            <div class="line"></div>
                            <h3 class="wow flipInX">{{ service.title }}</h3>
                        </div>
                    </div>
                {% endfor %}

            </div>
        </div>
    </div>

    <div class="videos">
        <div class="container">
            <div class="row">
                <h1 class="section-title">Videolar</h1>
                <div class="video-carousel owl-carousel owl-theme">
                    <div class="carousel-row">
                        {% for video in videos %}
                            <div class="col-sm-6 col-md-4">
                                <div class="gallery-item wow fadeInUp"
                                     data-wow-delay="{{ forloop.counter|data_wow_delay }}">
                                    <a class="video-link" href="{{ video.url }}">
                                        <div class="gallery-icon">
                                            <img class="img-responsive"
                                                 src="{% static "ginekolog/img/video-icon.svg" %}"
                                                 alt="">
                                        </div>
                                        <div class="gallery-img"
                                             style="background-image:url('{{ video.get_video_thumbnail_url }}')"></div>
                                    </a>
                                    <h5 class="gallery-text">{{ video.title | safe | truncatewords:"15" }}</h5>
                                </div>
                            </div>
                            {% if forloop.counter|divisibleby:"6" %}
                                </div>
                                <div class="carousel-row">
                            {% endif %}
                        {% endfor %}

                        </div>
                </div>
                <a class="btn-r" href="{% url "videos" %}?category=all">
                    Bütün videolar
                </a>
            </div>
        </div>
    </div>

    <div class="photos">
        <div class="container">
            <div class="row">
                <h1 class="section-title">Şəkillər</h1>
                <div class="photo-carousel owl-carousel owl-theme">
                    <div class="carousel-row">
                        {% for picture in pictures %}
                            <div class="col-sm-6 col-md-4">
                                <div class="gallery-item wow fadeInUp"
                                     data-wow-delay="{{ forloop.counter|data_wow_delay }}">
                                    <a class="photo-link" href="{{ picture.image.url }}">
                                        <div class="gallery-icon">
                                            <img class="img-responsive"
                                                 src="{% static "ginekolog/img/photo-icon.svg" %}"
                                                 alt="">
                                        </div>
                                        <div class="gallery-img"
                                             style="background-image:url('{{ picture.image.url }}')"></div>
                                    </a>
                                    <h5 class="gallery-text">{{ picture.title }}</h5>
                                </div>
                            </div>
                            {% if forloop.counter|divisibleby:"6" %}
                                </div>
                                <div class="carousel-row">
                            {% endif %}
                        {% endfor %}
                        </div>

                </div>
                <a class="btn-r" href="{% url "pictures" %}">Bütün şəkillər</a>
            </div>
        </div>
    </div>

    <div class="blog">
        <div class="container">
            <div class="row">
                <h1 class="section-title">Məqalələr</h1>
                <div class="blog-carousel owl-carousel owl-theme">
                    <div class="carousel-row">
                        {% for post in posts %}
                            <div class="col-sm-6 col-md-4">
                                <div class="blog-item wow fadeInUp"
                                     data-wow-delay="{{ forloop.counter|data_wow_delay }}">
                                    <div class="blog-details">
                                        <div class="blog-text">
                                            <h5>{{ post.title }}</h5>
                                            <p>{{ post.content|safe|truncatewords:"20" }}</p>
                                        </div>
                                        <div class="blog-img">
                                            <img class="img-responsive" src="{{ post.cover.url }}" alt="">
                                        </div>
                                    </div>
                                    <a href="{{ post.get_absolute_url }}" class="blog-btn">
                                        Daha ətraflı
                                    </a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-md-12 text-center">
                    <a class="btn-r" href="{% url "posts" %}">Bütün məqalələr</a>
                </div>
            </div>
        </div>
    </div>

    <div class="contact">
        <div class="map">
            <div class="contact-items wow bounceInLeft" data-wow-delay="0.7s">
                <div class="contact-item">
                    <h5 class="contact-item-title">Ünvan</h5>
                    <ul>
                        <li style="white-space: pre-wrap;">{{ doctors.first.address|safe }}</li>
                    </ul>
                </div>
                <div class="contact-item">
                    <h5 class="contact-item-title">Əlaqə</h5>
                    <ul>
                        {% for doctor in doctors %}
                            <li>{{ doctor.profession }}</li>
                            <li>{{ doctor.get_doctor_name }}</li>
                            <li>{{ doctor.phone_number }}</li>
                            <div class="contact-line"></div>
                            {% if forloop.counter|divisibleby:doctors.Count %}
                                <div class="contact-line"></div>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d97260.34098206263!2d49.799863058994454!3d40.378144490897796!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x403063737e96e061%3A0x5b925e8db0b28d35!2sBaku+Medikal+Plaza!5e0!3m2!1saz!2s!4v1520497498140"
                    width="100%"
                    height="100%"
                    frameborder="0"
                    style="border:0"
                    allowfullscreen>
            </iframe>
        </div>
    </div>

</section>